### ISSUE TITLE
[check_ceph_osd] says ok when an OSD is Down+out

### ISSUE THREAD

**Issue by kiranos** [valerytschopp/ceph-nagios-plugins#11]
Hi,

Thanks for this plugin, I have one question about check_ceph_osd, it would be nice if the below output generate a warning. An OSD is down but the status of OSD's are OK so we dont get a warning that an OSD is out. The OSD was faulty and was taken out by ceph itself.

```
OSD OK
Up OSDs: osd.1 osd.4 osd.7 osd.10
Down+In OSDs: 
Down+Out OSDs: osd.13
```

**Comment by valerytschopp** [comment]
I think using the option `--out` should do what you want, and throw a WARNING for a down/out OSD.
