### ISSUE TITLE
Have a variant of rgw plugin using the restful admin api

### ISSUE THREAD

**Issue by theanalyst** [valerytschopp/ceph-nagios-plugins#19]
We could have a variant of rgw plugin calling the same command using the restful api, this has an advantage of being able to be deployed on the admin or any other nodes and doesn't require the cephx keyring. The downside is that a user has to be created in advance with the necessary caps for this to be working.

**Comment by valerytschopp** [comment]
Hi theanalyst,
Have a look at https://github.com/valerytschopp/python-radosgw-admin/blob/master/radosgw/connection.py it already implement all the basic functionalities of the RadosGW admin API...

**Comment by theanalyst** [comment]
@valerytschopp ah nice, didn't know this will check out
