### ISSUE TITLE
--id option does not work on radosgw-admin in giant

### ISSUE THREAD

**Issue by TheMeier** [valerytschopp/ceph-nagios-plugins#6]
For me --id does not work in radosgw-admin, but -i does:

 /usr/bin/radosgw-admin -v
ceph version 0.87 (c51c8f9d80fa4e0168aa52685b8de40e42758578)

I know this is an ceph problem not yours but maybe using -i instead of --id in check_ceph_rgw is an option..

**Comment by valerytschopp** [comment]
Hi Christoph, do you still have a the problem or does 'radosgw-admin --id ID' work for you?

**Comment by TheMeier** [comment]
no it doesn't but i also figured that i can not get radosgw-admin to work at all as non-root. since i'm doing end-to-end test by fetching a file via s3 i currently do not need a seperate radosgw monitoring.

**Comment by valerytschopp** [comment]
Ok, thanks for the bug report. 
I've fix the 'radosgw-admin --id' problem in the code.
