### ISSUE TITLE
check_ceph_osd fails from remote host : failed to bind the UNIX domain socket

### ISSUE THREAD

**Issue by ksingh7** [valerytschopp/ceph-nagios-plugins#8]
@valerytschopp , first of all thanks for out-of-box working plugins.

I have been trying these plugins in my environment and check_ceph_osd does'nt seems to be working from a remote host, however its working from a localhost

```
[root@admin libexec]# ./check_nrpe -H storage0111 -c check_ceph_osd -a nagios /etc/ceph/client.nagios.keyring storage0111-ib
OSD ERROR: 2015-05-27 15:57:14.277582 7f810c20b700 -1 asok(0x7f8104000fc0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-client.nagios.3014269.140192094621760.asok': (13) Permission denied

[root@admin libexec]#
```

However if i execute it from a localhost , it simply works.

```

[root@storage0111 libexec]# ./check_ceph_osd --id nagios --keyring /etc/ceph/client.nagios.keyring --host storage0111-ib
OSD OK
Up OSDs: osd.0 osd.6 osd.10 osd.17 osd.21 osd.26 osd.30 osd.35 osd.40 osd.45
Down+In OSDs:
Down+Out OSDs:
[root@storage0111 libexec]#
```

FYI , check_ceph_health and check_ceph_mon are working fine from local as well as remote host. The problem is only with check_ceph_osd script.

Since you are the father of these scripts , any help wrt is appreciated.

**Comment by valerytschopp** [comment]
Sorry, we don't use nagios `check_nrpe`, but install the plugin directly on the ceph primary monitor...
I have no idea :(
